services:
  deskconn-router:
    image: xconnio/deskconn-router:latest
    container_name: deskconn-router
    env_file:
      - .env
    environment:
      DESKCONN_POSTGRES_HOST: host.docker.internal
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8080:8080"
      - "8081:8081/udp"
      - "8082:8082/udp"
      - "8083:8083"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    restart: unless-stopped
